trigger:
- main

pool: myhost

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    terraform init
    terraform apply -auto-approve
    cat /tmp/inv
  displayName: 'Run a multi-line script'